[package]
name = "registry-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
chrono.workspace = true
dotenvy.workspace = true
registry-core = { path = "../registry-core" }
registry-db = { path = "../registry-db" }
registry-storage = { path = "../registry-storage" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true

[dev-dependencies]
http.workspace = true
tower.workspace = true
